### ISSUE TITLE
LTP0是怎么来的？

### ISSUE THREAD

**Issue by refwww** [nws0507/DYRoomCheckIn#3]
我发现cookie没有LTP0，怎么也没有，不知道作者有没有研究过？
比如登录方式：手机登录 帐号登录 客户端一键登录等等..
又或者是浏览器？

**Comment by nvv5** [comment]
浏览器扫码登录成功后，会返回的。当然，pc端本地配置里保存的也有，我没测试过。其他cookie会通过这个ltp0请求获取。authlogin里有找到的利用ltp0的接口，可以看看

**Comment by refwww** [comment]
知道了，谢谢。
但ltp0有利也有弊，本来想着把脚本丢在服务器上挂机就完事了，但是发现脚本用了有ltp0的cookie后，电脑端正常观看的会被T下线，然后登录后 脚本又被T下线，

**Comment by nvv5** [comment]
我服务器用的都是隐私窗口重新登录一个

**Comment by refwww** [comment]
> 我服务器用的都是隐私窗口重新登录一个

妙啊，没想到还能这样，感谢
