### ISSUE TITLE
对不起大佬，这是小白的求助

### ISSUE THREAD

**Issue by malxy1234** [nws0507/DYRoomCheckIn#4]
大佬你好！我是一名小白。
我起初对python一窍不通，但是看完你的这个脚本让我下定决心去学。
然而我上网看了搜索cookies的办法后尝试，仍然出现了invaild syntax的问题。
请问大佬，到底我的语法错误在哪？我只是复制了cookies进去而已。
我搜索cookies的办法是在斗鱼的网页按F12，再搜寻，得出一大串的乱码。
请问我是对的吗？还是其实我从这里已经做错了。希望大佬能解答我的疑问，谢谢。

**Comment by nvv5** [comment]
f12控制台输入```document.cookie```  复制打印出来的就可以了吧  
出现```invaild syntax```的错误一般是python格式错误，你要看具体报错是哪一行，一般是缩进问题。

**Comment by malxy1234** [comment]
感谢大佬的回复。我首先想再问问大佬，到底是如何才能得到正确的cookie？
我透过百度，得到的答案是首先进去一个直播间，然后按F12。再通过搜索acf_did找到整条的COOKIE。
之后再用IDLE打开douyu_roomcheckin.py，再复制到第223行 COOKIE‘’之后，然后我尝试按F5运行，就会出现invaild syntax了。 请问我到底是哪里做错了，以及正确的COOKIE的格式是怎么样的呢。
是这样的吗？：dy_did:xxxxxxxxxxxxx ; acf_did:xxxxxxxxxxxxxxxxxx 这样的吗？
我找到的cookie包含acf_uid、acf_biz、acf_stk、acf_ct、acf_ltkid等字眼，但还有其他的...

烦请大佬解惑，小白的问题有点多，十分抱歉。

**Comment by nvv5** [comment]
你f12在```console```输入```document.cookie```打印的cookie全部复制进去就好  格式是```a=xxx; b=xxxx;  ``` 最后复制进去以后那行应该是```cookies='a=xxxx;b=xxxx;'```这种格式

**Comment by malxy1234** [comment]
大佬我大概理解了～谢谢大佬，换而言之我搜寻cookie的方法是错的。
但是我按照你说的步骤去在console输入document.cookie，只是显示了一些ERROR，如图。
请大佬告诉我的错误在哪，谢谢！
![error](https://user-images.githubusercontent.com/32539048/78161235-ba13a000-7477-11ea-8137-3f519622848c.jpg)

**Comment by nvv5** [comment]
emmm  这种问题希望你能百度一下 欢迎你提问  不过这类问题搜一下就可以找到答案的

**Comment by malxy1234** [comment]
！！！我成功了！ 谢谢大佬～
真的很感谢你，解答了我的疑问。
而且在这次以后我也下定决心去学习了，谢谢大佬！
不过我有最后一个问题，就是为什么这边显示0个主播已开播，0个主播未开播？
谢谢大佬解惑，更燃起了我学习的想法！
![success](https://user-images.githubusercontent.com/32539048/78162185-10351300-7479-11ea-940b-f705b8a60b54.jpg)

然后我是需要在希望他自动签到前几分钟才开启程式对吗，因为我看他运行一段时间就会出现初始化失败。谢谢大佬解惑～

**Comment by nvv5** [comment]
不需要管的，只要挂着就可以了，他会每5秒轮询一次检测关注列表中的主播有没有开播，检测到开播了就会签到。因为自用的问题，有一些小bug没有完善，不过不怎么影响使用。

**Comment by malxy1234** [comment]
嗯嗯我知道了，谢谢大佬解答我的疑问。
大恩大德，没齿难忘。
这边我先关闭了这个issue！，谢谢大佬。
